#1785 Logging when Audit page and Validation page are visible
ProjectSidewalk/SidewalkWebpage pull request #2222
Opened 2020-09-01 20:58 UTC by shokiami

Resolves #1785 

This PR makes it so that any visibility change of the audit and validation page are logged to the database.

Audit Task Interaction Table Example Entries:
<img width="426" alt="Screen Shot 2020-09-01 at 1 57 01 PM" src="https://user-images.githubusercontent.com/43970567/91905257-1bc07c00-ec5b-11ea-9b12-7276bfa67b75.png">

Validation Task Interaction Table Example Entries:
<img width="547" alt="Screen Shot 2020-09-01 at 1 52 54 PM" src="https://user-images.githubusercontent.com/43970567/91905267-20853000-ec5b-11ea-8a6a-1b3cf1fd2ccc.png">

2020-09-04 05:19 UTC, shokiami commented
@misaugstad I just wanted to let you know that, from my testing, I found that the visibilitychange event listener triggers whenever the webpage is fully obscured from view (e.g. when the user goes into another browser tab, hides the entire browser behind another application, or enters a different desktop), but not if any part of the webpage is visible (e.g. the user fills the screen with applications but the corner of the webpage is still barely visible).

2020-09-08 00:40 UTC, misaugstad commented
@shokiami do you know if there are alternatives that also take into account if the browser is partially hidden. Or is just out of focus is what we are really looking for.

2020-09-08 00:41 UTC, misaugstad commented
Like what you have sounds good, I would just expect there to be a way to know if our browser window is in focus or not

2020-09-12 00:33 UTC, shokiami commented
@misaugstad 
Boom! It's working perfectly. I finally managed to get the focus/blur event listeners to work. Sorry that took so long; it took me a while to figure out that it was supposed to be `window.addEventListener` not `document.addEventListener` 😅. Anyhow, here is what the audit task interactions table looks like after a bunch of clicking in and out of the webpage:
<img width="613" alt="Screen Shot 2020-09-11 at 5 27 18 PM" src="https://user-images.githubusercontent.com/43970567/92982792-be93aa00-f454-11ea-9de5-c22d2549f627.png">
Please let me know if you would like me to change the wording or the format of the entries.

2020-09-12 01:24 UTC, misaugstad commented
I think the only change I would want would be to include whether it is now in/out of focus in the action name instead of the note.

2020-09-13 01:36 UTC, shokiami commented
@misaugstad What do you think?
<img width="328" alt="Screen Shot 2020-09-12 at 6 35 32 PM" src="https://user-images.githubusercontent.com/43970567/93008188-d4719f80-f526-11ea-9ab8-fcd4f72651cb.png">

2020-09-14 20:42 UTC, misaugstad requested changes

2020-09-14 20:42 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/Main.js
> +        // Logs when the webpage's visiblity changes.
When you first add the event listeners, can you first do a check for whether the page is in/out of focus and log that?

2020-09-14 20:42 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/Main.js
> +            svl.tracker.push("GainedFocus")
Can you change it to PageGainedFocus and PageLostFocus

2020-09-14 22:05 UTC, misaugstad commented
Do you know if this works on mobile?

2020-09-14 22:48 UTC, misaugstad commented
Then can you edit [this wiki page](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Descriptions-of-Logged-Events) with the appropriate checkmark or X for mobile use?

2020-09-15 22:30 UTC, shokiami commented
@misaugstad 
Please let me know what you think of my edits!
Also, it seems to be working for mobile. However, there is one issue: it logs twice when the page gains visibility (I don't know why).
<img width="224" alt="Screen Shot 2020-09-15 at 3 28 01 PM" src="https://user-images.githubusercontent.com/43970567/93271457-2b19ec00-f768-11ea-8ccd-b9d6cf8e9f0d.png">

2020-09-16 00:38 UTC, misaugstad commented
I'm assuming you're using an iPhone? I am as well and am getting the same bug. Seems to be a [webkit bug](https://stackoverflow.com/questions/42529773/why-does-ios-safari-fire-window-focus-event-twice) so it is not on us. I think the only issue I found with your code was that the first PageGainedFocus log on the validation page has the mission_id as null. So I think you just want to wait to add the listeners and do that initial check for page focus until the mission id has been initialized. Working well on the audit page!

2020-09-16 05:36 UTC, shokiami commented
@misaugstad How does that look?

2020-09-16 20:51 UTC, misaugstad approved these changes
Looks good!

2020-09-16 20:51 UTC, merged