2305 navbar messed up after signing in
ProjectSidewalk/SidewalkWebpage pull request #2326
Opened 2020-10-21 04:26 UTC by uditpatwal

Resolves #2305 

**This is how the navbar looked like before the fix:**
![broken-navbar-after-signin](https://user-images.githubusercontent.com/34140897/96672030-482a7780-1331-11eb-89ef-aa4e6a291652.png)

**This is how the navbar looks like after the fix:**
![fixed-navbar-after-signing-in](https://user-images.githubusercontent.com/34140897/96672996-77da7f00-1333-11eb-845b-d102aab701af.PNG)

**How issue was fixed**
Go to app/views/navbar.scala.html and at line ~122 change `id="navbar-dropdown-list"` to `id="navbar-data-dropdown-list"`. This changes the id of the Data dropdown button. I think this bug was happening because the Sign-In and Data buttons had the same id's of `navbar-dropdown-list`. So then when script was changing the Data button instead of the Sign-In button.

**Potential bugs/issues**
If there were scripts that call the Data button, referencing the id `navbar-dropdown-list`, then there will be a problem because the new id for the Data button is `navbar-data-dropdown-list`. It will now reference the Sign-in button with the same id. I did not see any conflicts when checking, but I am not 100% sure.

2020-10-22 21:20 UTC, misaugstad requested changes
Nice find! Can you just also rename the other drop down menu's id to be "navbar-user-dropdown-list"? 

The dropdown list with the username was added first, and the data drop down was just recently added, so all other references to "navbar-dropdown-list" are meant for the user dropdown. So all other references to "navbar-dropdown-list" can be changed to "navbar-user-dropdown-list".

2020-10-22 22:43 UTC, uditpatwal commented
Actually hold on, I still think there is a bug.

2020-10-22 22:49 UTC, uditpatwal commented
I took the screenshot above after signing in, not registering for an account. I just tried with registering, and the solution above did fix the issue, but for some reason there is no black outline around the username after signing up. I am working on it.

![where-is-black-box](https://user-images.githubusercontent.com/34140897/96937938-3ebb1f80-1497-11eb-9367-79738fcce198.PNG)

2020-10-23 22:51 UTC, uditpatwal commented
I added `class="navbarBtn"` to the signed-In user template at the bottom of app/views/navbar.scala.html in the <a> tag for `nav-user-dropdown`. I think this also fixes the issue with #2330

2020-10-23 23:00 UTC, jonfroehlich commented
We need consistent naming here. I don’t think we should use camelCase and dashes styles for names. I think we mostly use latter, right?

Sent from my iPhone

> On Oct 23, 2020, at 3:51 PM, Udit Patwal <notifications@github.com> wrote:
> 
> ﻿
> I added class="navbarBtn" to the signed-In user template at the bottom of app/views/navbar.scala.html in the tag for nav-user-dropdown. I think this also fixes the issue with #2330
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-23 23:15 UTC, misaugstad commented
Yeah it should be navbar-btn. It's a class name that someone else made in the past, but since you're here @uditpatwal could you change it? :grin: thank you!

2020-10-23 23:20 UTC, uditpatwal commented
I got it!

2020-10-29 21:31 UTC, uditpatwal commented
#2345

2020-11-02 20:11 UTC, misaugstad approved these changes
Looks much better, thanks @uditpatwal !

2020-11-02 20:11 UTC, merged