2310-Leaderboard-Polishing
ProjectSidewalk/SidewalkWebpage pull request #2398
Opened 2020-12-01 23:10 UTC by jacknussbaum

Resolves #2310 

Adds encouragement messages and links to the bottom of the leaderboard page, bolds and hyperlinks a user's username on the leaderboard if that user is signed in.

**Signed out:**
![image](https://user-images.githubusercontent.com/71039842/100806588-8f526080-33e5-11eb-8616-a3ab6068c641.png)

**Signed in:**
![image](https://user-images.githubusercontent.com/71039842/100806630-a729e480-33e5-11eb-8ff5-963a8cedc2bb.png)

2020-12-02 20:40 UTC, misaugstad commented
I think for the hyerlinked username, we probably want underline instead of bold. I also think that the blue looks kind of ugly in the table... @jonfroehlich what do you think? Here is what it looks like with/without blue. Do you think without blue looks a lot better? Does it still seem to clearly be a hyperlink with just the underline?

![Screenshot from 2020-12-02 12-37-38](https://user-images.githubusercontent.com/6518824/100928738-73a99180-349b-11eb-827f-9c5203aec5b6.png)
![Screenshot from 2020-12-02 12-38-54](https://user-images.githubusercontent.com/6518824/100928743-74dabe80-349b-11eb-926d-668c52566c0b.png)

And if we change the color of the hyperlink in the table, should we also change it at the bottom of the page for consistency?

2020-12-02 20:42 UTC, jonfroehlich commented
Agree that blue looks ugly but people associate links with blue so maybe keep it?

Sent from my iPhone

> On Dec 2, 2020, at 12:40 PM, Mikey Saugstad <notifications@github.com> wrote:
> 
> ﻿
> I think for the hyerlinked username, we probably want underline instead of bold. I also think that the blue looks kind of ugly in the table... @jonfroehlich what do you think? Here is what it looks like with/without blue. Do you think without blue looks a lot better? Does it still seem to clearly be a hyperlink with just the underline?
> 
> 
> 
> 
> And if we change the color of the hyperlink in the table, should we also change it at the bottom of the page for consistency?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-02 20:43 UTC, jacknussbaum commented
That was my thought as well.. its not great but it definitely is clear that its a link.

2020-12-02 20:50 UTC, misaugstad commented
Yeah I think that makes sense. So just change from bold to underline and that should be good.

2020-12-03 03:52 UTC, misaugstad requested changes
Just a couple more minor things

2020-12-03 03:52 UTC, misaugstad commented on app/views/leaderboard.scala.html
> +                        @if(user && user.get.role.getOrElse("") != "Anonymous" && stat.asInstanceOf[LeaderboardStat].username == user.get.username){
Add space between `)` and `{` as per [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide)

2020-12-03 03:52 UTC, misaugstad commented on app/views/leaderboard.scala.html
> +<h4 style="text-align: center">
Can you add this style stuff to main.css next to the rest of the leaderboard stuff? You'll probably need to add an `id` for the header.

2020-12-03 03:52 UTC, misaugstad commented on app/views/leaderboard.scala.html
> +                        }else{
Can you try and add spaces around the brackets as per [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide) wherever possible in the code you added? I know that template scala prevents you from doing one or two things (like you can't do the `@if (` I would want, you have to do `@if(` instead). But you can do most of it.

2020-12-03 03:52 UTC, misaugstad commented on conf/messages.en
> +leaderboard.encouragement.no.user = Sign up to track your progess!
Can you turn this into a hyperlink to the sign up page?

2020-12-03 03:52 UTC, misaugstad commented on app/views/leaderboard.scala.html
> +
I think you added 3 extra lines at the end here that you don't need.

2020-12-03 23:58 UTC, jacknussbaum commented
Okay. Sign up page is now linked. I changed around some formatting in the messages file, think it makes more sense now.

2020-12-09 03:10 UTC, misaugstad approved these changes
Looks great, thank you! I just made the very small change of only hyperlinking "sign up" instead of the entire sentence "sign up to track your progress" since that's sort of what we've been doing elsewhere.

2020-12-09 03:10 UTC, merged