2381 minor changes to admin playback tool
ProjectSidewalk/SidewalkWebpage pull request #2417
Opened 2020-12-23 23:08 UTC by uditpatwal

Resolves #2381 

**What I did**
Added pause feature.
Added ability to change speed multiplier, max pause time, and fill time.
Added replay button.

**What still needs to be done**
Restart blue bar.
Add total watch time.

2021-01-07 22:14 UTC, misaugstad requested changes
I didn't do a full review, because i know you're in the middle of working on this. But here are a couple small notes:

1. I had an issue in the first task I tried to play, where it said that the total watch time was NaN, which made it so that the blue progress bar didn't move forward at all.
1. As mentioned over Slack, since the state doesn't get totally reset from the restart button, it should just be taken away, and we can always just restart by refreshing the page.

2021-01-07 22:14 UTC, misaugstad commented on app/views/admin/task.scala.html
> +                    <div id="watchTime">
make sure this is in "kebab-case" instead of "camelCase"

2021-01-11 20:53 UTC, misaugstad commented
Note for the future: Including screenshots is really helpful, because I can then give feedback on visual things without needing to check out your branch and run the code.

In any case, can you round to just one number after the decimal place (or maybe no decimal at all?). And can you split that up into "Current time" and "Total time". I didn't even notice that the total time was listed there for awhile. Loving pause/play feature though!!
![Screenshot from 2021-01-11 12-49-53](https://user-images.githubusercontent.com/6518824/104236515-8785d300-540b-11eb-8432-c5c64f4e4833.png)

2021-01-19 00:39 UTC, uditpatwal commented
Included a screenshot on how it looks!

![admin-playback](https://user-images.githubusercontent.com/34140897/104974090-be885580-59c4-11eb-87b5-8bbe120adf81.PNG)

2021-01-19 00:41 UTC, misaugstad commented
Great, can you add the time unit? I'm assuming seconds?

2021-01-19 00:46 UTC, uditpatwal commented
Screenshot of above change!

![admin-playback](https://user-images.githubusercontent.com/34140897/104974392-d57b7780-59c5-11eb-86a0-b8cc23ac9af1.PNG)

2021-01-19 00:49 UTC, misaugstad commented
Great. Can you do the same for the wait/fill time too? Aaand maybe convert that from ms to seconds..? So it would look like "Max wait time (s):" and "Fill time (s):", with the default being 5 and 0.5. Note that you don't need to put the unit after the number or after the box, just in parens in the title.

2021-01-21 21:32 UTC, uditpatwal commented
Screenshot of above change to all times in seconds.
![admin-playback](https://user-images.githubusercontent.com/34140897/105414978-32657080-5c06-11eb-8dd8-be562102d084.PNG)

2021-01-25 23:30 UTC, misaugstad approved these changes
In the interest of getting this PR out today, I made a couple quick style edits myself! Left comments on the PR showing what I changed. Great work @uditpatwal !

2021-01-25 23:30 UTC, misaugstad commented on public/javascripts/Admin/src/Admin.Task.js
> +            let speedMultiplier = document.getElementById('speed-multiplier').value;
I changed these to be `let` instead of `const` and made them lowercase.

2021-01-25 23:30 UTC, misaugstad commented on public/stylesheets/adminTask.css
> +}
Added a newline to the end of the file.

2021-01-25 23:30 UTC, merged