2454 indicate expired pano
ProjectSidewalk/SidewalkWebpage pull request #2488
Opened 2021-03-10 22:11 UTC by mcdoerr

Resolves #2454 

Adding a new look for a pano that has expired imagery. We indicate this by moving the color to be a .5 opacity border, with a light grey center. 

To implement this, changing the Slick to include an additional join with the gsv_data table to include the expired table. Locally, this doesn't seem to affect performance on a noticeable level. The type is BooleanOption because some columns may be null (according to errors that arose from just using Boolean). 

I spot tested that the expired labels match the labels that don't have imagery.

Here is an image of the expired panos, with some non-expired panos for contrast.
<img width="426" alt="Screen Shot 2021-03-08 at 12 36 33 PM" src="https://user-images.githubusercontent.com/45296521/110704755-a528ac00-81b2-11eb-833a-c5d0490cf8dc.png">

2021-03-10 23:32 UTC, misaugstad requested changes
Okay, so you noticed a problem in the query here (some columns were being included and then never used). And it made me realize that this query was looking pretty bad and I couldn't help myself and I did a quick rewrite of it :sweat_smile: It's a little shorter and simpler. And instead of setting the latitude/longitude to 0 if they are null, it just filters them out now. Setting them to 0 just doesn't make sense :shrug: 

>The type is BooleanOption because some columns may be null (according to errors that arose from just using Boolean).

I switched the join you made from a "left join" to an "inner join", which means that a row is included in the join only if there is an entry in _both_ tables that matches the description (`_l.gsvPanoramaId === _gsv.gsvPanoramaId`). So now the `expired` column doesn't need to be an Option type! I made that change during my rewrite. Nice work on figuring out how to do all of that though!

Okay, now on to the visual stuff! The issue I'm having is that the labels with expired imagery seem to "pop" more when the map is zoomed out (which is how the page loads). Adding some example images below. Maybe we need to try decreasing the opacity of the border a bit more? Or decreasing it's thickness? Not sure. But I think that future iterations should have both zoomed in and zoomed out screenshots.

![Screenshot from 2021-03-10 14-41-36](https://user-images.githubusercontent.com/6518824/110711199-fdac7900-81b3-11eb-8208-4231d56689bb.png)
![Screenshot from 2021-03-10 14-40-26](https://user-images.githubusercontent.com/6518824/110711201-fedda600-81b3-11eb-87b7-ce67c111929e.png)

2021-03-10 23:32 UTC, misaugstad commented on app/models/label/LabelTable.scala
> -    } yield (_labels.labelId, _labels.auditTaskId, _labels.gsvPanoramaId, _labelTypes.labelType, _labels.panoramaLat, _labels.panoramaLng)
Thanks for noticing that we weren't even using `panoramaLat` and `panoramaLng`!  This query was written 4 years ago, and from the beginning they were never used :upside_down_face:

2021-03-10 23:32 UTC, misaugstad commented on public/javascripts/Choropleths/InitializeSubmittedLabels.js
> +                if (feature.properties.expired) {
What happens if `params.includeLabelColor` is `false`, but `feature.properties.expired` is `true`? Then I think you'd be unintentially changing the look of those maps. You should probably just do:
```
if (params.includeLabelColor) {
    if (feature.properties.expired) {
        style.fillColor = 'lightgrey';
        style.color = colorMapping[feature.properties.label_type].missingPanoStrokeStyle;
    } else {
        style.color = colorMapping[feature.properties.label_type].strokeStyle;
    }
}
```

2021-03-11 00:14 UTC, mcdoerr commented
Yeah, I agree about the panos popping, but I think what's actually popping is the "Other" category, which has a gray (instead of light gray) center and the border is not transparent at all. Here's a non-zoomed image without the expired pano new look, so what is currently on the website of the "Other" pano popping. 
<img width="113" alt="Screen Shot 2021-03-10 at 4 06 56 PM" src="https://user-images.githubusercontent.com/45296521/110716233-f8efc100-81c3-11eb-89cd-ac8fbc346961.png">

2021-03-11 00:19 UTC, misaugstad commented
Oops, thank you! I think that I had a No Sidewalk and an Other label next to each other, and accidentally clicked on the No Sidewalk label twice, so I thought that that's what I was looking at, my bad!! Let me take another look real quick.

2021-03-11 00:22 UTC, mcdoerr commented
It seems to me that the Other category when stacked on top of each other because it's very zoomed creates a lot of contrast since the opacities stack to produce a very dark grey. Not sure what the fix for that would look like, seems like maybe another issue?

I'm a tad worried about expired panos being confused with "Other" or "No Sidewalk" though

2021-03-11 00:32 UTC, misaugstad commented
I'm playing around with the opacity, and now that I'm seeing it zoomed out as well, I think that I like something more like 0.8. Here are a couple pics. The difference between "Other" and the labels with expired imagery is clear here as well.

![Screenshot from 2021-03-10 16-30-24](https://user-images.githubusercontent.com/6518824/110717581-2cc7e800-81be-11eb-9afc-b52e93e963a4.png)
![Screenshot from 2021-03-10 16-31-36](https://user-images.githubusercontent.com/6518824/110717583-2d607e80-81be-11eb-8a85-5d320013ee6e.png)
![Screenshot from 2021-03-10 16-31-51](https://user-images.githubusercontent.com/6518824/110717588-2e91ab80-81be-11eb-8839-a476c290246e.png)
![Screenshot from 2021-03-10 16-32-08](https://user-images.githubusercontent.com/6518824/110717590-2f2a4200-81be-11eb-8c65-74b0d0d9ae9f.png)

2021-03-11 00:43 UTC, misaugstad commented
@mcdoerr how do those look to you? you had said that you prefer the opacity of 0.5, do you still prefer that?

2021-03-11 00:45 UTC, mcdoerr commented
I was looking at it some more, and I've found some labels that have imagery but have the expired column marked true for some reason (verified it is true in the database). Any idea why that might be happening? 

One of the panos I found with this issue is 'OEjCJD6XfUnADm8KaIoIvw'.

I still like the .5 because I think it makes it less likely to be clicked on, but I don't feel super strongly about it!

2021-03-11 00:47 UTC, misaugstad commented
>I still like the .5 because I think it makes it less likely to be clicked on, but I don't feel super strongly about it!

I think that .5 can sometimes just make it look like there is no color at all. It's kind of hard to see any purple here:
![Screenshot from 2021-03-10 16-47-00](https://user-images.githubusercontent.com/6518824/110718675-5255f100-81c0-11eb-80cd-6c0c5a19ec22.png)

2021-03-11 00:51 UTC, misaugstad commented
>I was looking at it some more, and I've found some labels that have imagery but have the expired column marked true for some reason (verified it is true in the database). Any idea why that might be happening?

Hmm... It's possible that when we checked if there was imagery at some point, there may have been some network error or something. And it might be hard to distinguish between that and Google just not having the imagery available. So I suppose it's possible that a small number of images are marked incorrectly that way. I think that when we implement #2458 we should consider also looking at images that have been marked as expired to double check!

2021-03-11 00:52 UTC, mcdoerr commented
Oh yeah that screenshot definitely convinces me, I'll update it to .8, I agree

2021-03-11 01:02 UTC, mcdoerr commented
Ok, that sounds good regarding #2458!

2021-03-11 01:09 UTC, misaugstad approved these changes
Looks good!! Thanks @mcdoerr !

2021-03-11 01:09 UTC, merged