1236 update street priority values while auditing
ProjectSidewalk/SidewalkWebpage pull request #2529
Opened 2021-04-09 22:30 UTC by uditpatwal

Resolves #1236

**What I added**
The front end updates its local street priority values whenever it submits data to the backend. Now users have up to date information from the back end about street edge priorities.

Not ready for review yet.

2021-05-20 16:26 UTC, uditpatwal commented
@misaugstad ready for review!

2021-06-02 21:35 UTC, misaugstad requested changes
Nice work on this! The code is working well, and I'm super excited to have this feature! The code could use some reworking though to make it more readable. I go into detail on that stuff throughout the comments and below :)

1. It looks like you need to be filtering out streets that are not in the user's current neighborhood. It doesn't cause any harm, but I'm getting console errors at least because the front-end only knows about streets in it's current neighborhood.
2. Instead of adding 3 parameters to the `TaskPostReturnValue`, could you instead just add one, but create a new class to hold all that info? It might look something like
    ```
    case class UpdatedStreets(updateTime: Timestamp, newStreetPriorities: List[StreetEdgePriority])
    ```
    where `StreetEdgePriority` is already a case class in `StreetEdgePriorityTable.scala` which has it's own `toJSON` method that you can use later. I think that there are a lot of positive things that come out of this change.
        1. You no longer have to keep track of indexes on the front-end. There are places where you are looping through the arrays by index, and you have to use the same index in both arrays. Instead, you won't have to use indexes at all, you should be able to just grab the street edge ID through a named field, which will make the code easier to read.
        2. It makes it easy to replace those three mutable variables (`streetEdgeIdsAfterTime`, `newStreetEdgePriorities`, and `timePerformedQuery`) with just a single immutable `val`. I mention how that could work in a comment in the code.

2021-06-02 21:35 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/data/Form.js
> +        timeLastQuried : new Date().getTime() // Assuming that Form is created when TaskContainer is created
I would change the comment to say something like "The priorities are up-to-date when the page loads". Again, would rename to something like `lastStreetPriorityUpdate`.

2021-06-02 21:35 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/data/Form.js
> +
Seems accidental

2021-06-02 21:35 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/data/Form.js
> +                    // Update the time the database performed the query to update our local task priorities with
This comment is just overly wordy and kinda confusing. Like I know what's going on, and I still had to read it 3+ times to get what you were going for here lol

2021-06-02 21:35 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/data/Form.js
> +
not necessary

2021-06-02 21:35 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/task/Task.js
> +        let oldPriority = properties.priority;
I think this might be left over from an old implementation or debugging? Not seeing it used anywhere else.

2021-06-02 21:35 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/task/TaskContainer.js
> +                        console.log("initNextTask");
just remove log statement

2021-08-10 03:27 UTC, misaugstad approved these changes
Okay I addressed the comments that I had added earlier, so this is good to go!

2021-08-10 03:27 UTC, merged