2131 Changing Ableist Language
ProjectSidewalk/SidewalkWebpage pull request #2542
Opened 2021-04-22 03:48 UTC by jiamae

Resolves #2131 

Changed all instances of "walk" and "step" to other language that isn't ableist

2021-04-22 18:08 UTC, misaugstad commented
@jiamae can you revert the changes to the `docker-compose.yml` file that you accidentally committed? Whenever you are preparing files to commit, make sure to check carefully that you are only including the files that you meant to edit! If you accidentally commit the API key like that, it's now been exposed publicly and I have to reset it for everyone :grin:

2021-04-22 18:18 UTC, jiamae commented
@misaugstad OMG SORRY I totally didn't catch that :(

2021-04-22 18:21 UTC, misaugstad commented
No worries! It happens from time to time! And it's also a problem of the system we have set up where you have files you need to edit that are not part of the `.gitignore`.

2021-05-06 04:17 UTC, jiamae commented
These are the ones I can't find while playing around with it:

"...the Google Street View interface is akin to a 3-dimensional interface, similar to moving about in the real world. When you place a label, we convert the 3D position of the label to a 2D lat/long position. However, once you move to a new location, we cannot accurately recompute the label's position in 3D for that new view. See, we told..."

"If you move from one image to another and things change (temporary obstacles like construction are removed..."

"Explore for for __PLACEHOLDER__ and find all the sidewalk accessibility attributes"

2021-05-14 23:00 UTC, misaugstad commented
>"...the Google Street View interface is akin to a 3-dimensional interface, similar to moving about in the real world. When you place a label, we convert the 3D position of the label to a 2D lat/long position. However, once you move to a new location, we cannot accurately recompute the label's position in 3D for that new view. See, we told..."

This one is just on the /help page, if you search for some of the text, you should find it.

>"If you move from one image to another and things change (temporary obstacles like construction are removed..."

Similarly, you can just find this at /labelingGuide

>"Explore for for PLACEHOLDER and find all the sidewalk accessibility attributes"

And I got that one to show up in the right UI under the "Current Mission" header when it is a user's first mission (after the tutorial). Here's how I figured that would be the place (to help with learning the code base):

This is the line you edited:
```
"message-first-mission": "Explore for for __PLACEHOLDER__ and find all the sidewalk accessibility attributes",
```
I searched fro `message-first-mission` throughout the code and found it at line 20 of `StatusFieldMission.js`. It's in a block of code that looks like this:
```
} else if (svl.missionContainer.isTheFirstMission()) {
    missionMessage = i18next.t('right-ui.current-mission.message-first-mission');
```
And `svl.missionContainer.isTheFirstMission()` is the hint that it was probably during someone's first mission.

Okay, thanks for looking through these and testing! Time for the code review :)

2021-05-14 23:08 UTC, misaugstad requested changes
Okay just two small changes! Then I'll add Spanish translations and we can merge :) Thanks again for going through and checking that all of these are actually used!

2021-05-14 23:08 UTC, misaugstad commented on app/views/help.scala.html
> +                                Yes, you're right, labels do disappear after you move in Google Street View interface
Ahh, can you actually remove the word "interface" as well?

2021-05-14 23:08 UTC, misaugstad commented on public/locales/en/audit.json
> +            "message-first-mission": "Explore for for __PLACEHOLDER__ and find all the sidewalk accessibility attributes",
You accidentally added the word "for" an extra time, oops!

2021-05-17 23:30 UTC, misaugstad approved these changes
Thanks @jiamae !

2021-05-17 23:30 UTC, merged