#2840: Updated gallery cards for label types that do not support severity ratings
ProjectSidewalk/SidewalkWebpage pull request #2954
Opened 2022-07-01 13:27 UTC by GPA0VERKD

Resolves #2840

Changed Gallery cards with unsupported severity ratings to have grayed out severity ratings, as well as a tooltip that, wehn hovered over, explains why they have no rating.

##### Before/After screenshots (if applicable)
Before:
![image](https://user-images.githubusercontent.com/77756028/176738015-d7ab975f-7626-49df-a3c2-dc219e886eb5.png)

After:
![image](https://user-images.githubusercontent.com/77756028/176737894-5fffb02a-4c10-48e9-81f0-3e9350eb391d.png)

##### Testing instructions
1. Go to the gallery tab
2. Under the "Show" drop down on the left, hit "Pedestrian Signal," or any label type that does not support severity ratings. (if the server you're working on doesn't have any pedestrian signals tagged, go into the audit tab and throw in a couple random pedestrian signal labels, not in production server ofc!!!)
3. Check that the Severity Rating is grayed out on all cards, and that a tooltip is there. When hovered over, a message box should appear.
4. Check in all languages!

##### Things to check before submitting the PR 
- [x] I've written a descriptive PR title.
- [x] I've added/updated comments for large or confusing blocks of code.
- [x] I've included before/after screenshots above.
- [x] I've asked for and included translations for any user facing text that was added or modified.

2022-07-01 18:29 UTC, misaugstad commented
I think that we can skip out on the '?' icon and just have the tooltip on the grayed out section. Do you have this on the expanded view when you click on a card as well?

2022-07-05 19:27 UTC, GPA0VERKD commented
Since we dont have a grayed out image for the smiley faces in the expanded view I just made them grayed out circles when there's no severity rating, does that work?

2022-07-05 19:34 UTC, misaugstad commented
There's this CSS property called `filter` that you can apply to an image. I just tested out setting `filter: opactity(0.5)` to one of the smileys and it looks like it's grayed out :ok_hand: 
![Screenshot from 2022-07-05 12-33-26](https://user-images.githubusercontent.com/6518824/177402212-408f18d1-fd3b-4927-ad69-abfcccb16072.png)

2022-07-06 20:11 UTC, misaugstad commented
I think that what you did is make it so that whenever a label doesn't have severity, you show the "unsupported" tooltip. But we actually only wanted to show this tooltip for the two label types where you aren't even able to add a severity rating: "Can't see the sidewalk" and "Pedestrian signal".

This does make me realize that we should do the grayed out with a tooltip for other label types if severity isn't provided as well. But that tooltip should just say that the user did not provide a severity rating.

In addition, the Can't See the Sidewalk label type is still showing no severity rating at all!

Here's screenshots with the various bits of incorrect behavior:
![Screenshot from 2022-07-06 13-01-40](https://user-images.githubusercontent.com/6518824/177634624-eb3bce33-1bdd-4374-82e4-b13ea39cd1d1.png)
![Screenshot from 2022-07-06 13-03-28](https://user-images.githubusercontent.com/6518824/177634628-13afa002-cbe6-4e51-b849-3863d255c195.png)
![Screenshot from 2022-07-06 13-02-09](https://user-images.githubusercontent.com/6518824/177634632-72640b41-9d6c-419a-98cc-ab94de2edcb3.png)

2022-07-18 18:54 UTC, misaugstad commented
Here's the one thing from the list above that I think you missed!

>This does make me realize that we should do the grayed out with a tooltip for other label types if severity isn't provided as well. But that tooltip should just say that the user did not provide a severity rating.

2022-07-19 22:12 UTC, misaugstad commented
A few more notes!
1. I made an update myself to remove old severity ratings for Pedestrian Signal labels since they were allowed for a couple weeks there. The existence of that data was causing bugs here, and I figured that wasn't worth it. So I cleaned up my old mess :)
2. Can you change this text slightly to say "A severity rating was not provided for this label"
    ![Screenshot from 2022-07-19 13-52-35](https://user-images.githubusercontent.com/6518824/179856878-add52c68-bfff-4a83-9a4a-c2b2c9f96880.png)
4. The expanded view tooltip is off center
    ![Screenshot from 2022-07-19 12-38-50](https://user-images.githubusercontent.com/6518824/179857034-c3a3b56f-045a-4ebb-8d2b-1c590f3232fc.png)
6. The grayed out text looks really bad on validated labels. This is because you're changing the font color to lightgray. You should probably just be keeping it as black and reducing the opacity.
    ![Screenshot from 2022-07-19 13-52-40](https://user-images.githubusercontent.com/6518824/179857078-dfcc5617-05ee-4c6f-a5ec-d9e143fce384.png)

Those last two should have become clear with extensive testing, so I challenge you to step up your code testing game in future iterations and PRs! ;)

2022-07-28 17:46 UTC, GPA0VERKD commented
@misaugstad Ready for another review!

2022-08-02 17:45 UTC, misaugstad requested changes
Just added some super minor style changes. Everything is working great though! Just about ready to merge!

2022-08-02 17:45 UTC, misaugstad commented on public/javascripts/Gallery/src/displays/SeverityDisplay.js
> +    // list of label types where severity ratings are not supported
Can you make the small edits to the comments to fit the [style guide](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Style-Guide)?

2022-08-02 17:45 UTC, misaugstad commented on public/javascripts/Gallery/src/displays/SeverityDisplay.js
> +            holder.classList.add('modal-no-severity-box')
It looks like this CSS class isn't specific to there being no severity (even though that's what's motivating the change), so maybe change the name to something that isn't specific to a lack of severity?

2022-08-02 17:45 UTC, misaugstad commented on public/javascripts/Gallery/src/displays/SeverityDisplay.js
> +            if (unsupported || !severity) {
Can we switch to checking specifically if `severity` is null or undefined (not sure which it is in this case). I think I'd prefer that over checking if it is falsey

2022-08-02 17:45 UTC, misaugstad commented on public/javascripts/Gallery/src/displays/SeverityDisplay.js
> +            if (unsupported){
missing that whitespace between the `)` and `{` ;)

2022-08-05 18:32 UTC, GPA0VERKD commented
Ready for another check!

2022-08-08 16:55 UTC, misaugstad approved these changes
Looks good, thanks @GPA0VERKD :)

2022-08-08 16:55 UTC, merged