2889 add user id to attribute api
ProjectSidewalk/SidewalkWebpage pull request #3040
Opened 2022-10-03 05:20 UTC by zoekaputa

Resolves #2889 

Adds User Id as a property returned from the `attributesWithLabels` API and a list of user ids to the `attributes` API. In both of these additions, the corresponding user id(s) are found by querying the `audit_task` table.

##### Before/After screenshots (if applicable)
`attributesWithLabels` API Before:
<img width="1052" alt="Screen Shot 2022-10-02 at 10 12 00 PM" src="https://user-images.githubusercontent.com/50668250/193505648-13335b35-2101-49e6-8e35-af67545e73c6.png">

`attributesWithLabels` API After:
![image](https://user-images.githubusercontent.com/50668250/193505511-d20c7206-ec98-4fb0-8c4c-8bc3c31c6ad8.png)

`attributes` API Before:
<img width="1035" alt="Screen Shot 2022-10-02 at 6 41 02 PM" src="https://user-images.githubusercontent.com/50668250/193505606-f1619975-406b-4ba6-981d-046f43fe4459.png">

`attributes` API After:
![image](https://user-images.githubusercontent.com/50668250/193505525-836c12aa-8c2a-4830-a298-db9bff06689d.png)

##### Testing instructions
1. Navigate to the API page.
2. Use the example API calls for `attributesWithLabels` and `attributes` to confirm that the returned data contains a user id and a list of user ids, respectively. Also try editing the parameters of the calls for other test scenarios.
3. Requesting and displaying the data visually (through a shapefile), is especially useful when comparing labels' user ids to attributes' user id lists.

2022-10-17 22:51 UTC, misaugstad requested changes
Seems to work well!! Just added a few comments about improving query efficiency and renaming things. Shouldn't be too bad!

2022-10-17 22:51 UTC, misaugstad commented on app/controllers/ProjectSidewalkAPIController.scala
> +        "Label Description,User Id"
We've been using 'ID' instead of 'Id' for the rest of the column headers, so let's keep it consistent here.

2022-10-17 22:51 UTC, misaugstad commented on app/models/attribute/GlobalAttributeTable.scala
> +      "users" -> Json.obj(
Let's just add a `user_ids` field to the `properties` object instead of making something that is separate from `properties`.

2022-10-17 22:51 UTC, misaugstad commented on app/models/attribute/GlobalAttributeTable.scala
> +    val userIds = """SELECT global_attribute.global_attribute_id, array_to_string(array_agg(DISTINCT audit_task.user_id), ',') AS users_list
For the sake of query efficiency, I think that you should be able to add this to the `imageDates` subquery by adding a join with the `audit_task` table. But let me know if there's something I'm missing here. I also saw that you left joined with this subquery when I would have thought that you could have done a inner join, so maybe I missed something.

2023-02-07 23:20 UTC, misaugstad approved these changes
Thanks for finishing this up @zoekaputa!! I made two small changes:
1. I simplified the JSON output for the list of users from
    ```
    users: {
      user_ids: [ ... ]
    }
    ```
    to
    ```
    users: [ ... ]
    ```
2. When I asked you to combine two subqueries for efficiency, there were situations where you could get duplicate user_ids in the list. This is because the inner group by gave you a comma-separated string of user_ids (grouped by `attribute_id` and `pano_id`), and then the outer group by (on just the `attribute_id`) did a `DISTINCT` on those comma-separated strings and combined them.

    An example: if `user1` labeled the same issue from both `pano1` and `pano2`, and `user2` labeled that issue from only `pano1`, and all three were then clustered into one attribute, `attribute1`. Then when you group by `attribute_id` and `pano_id`, you would end up with these two rows:
    ```
    (attribute1, pano1, "user1,user2")
    (attribute1, pano2, "user1")
    ```
    In your next group by, "user1,user2" is not equal to "user1", so your `DISTINCT` would include both of them. And the final output would be "user1,user2,user1".

    I was able to test this out locally, pic below! I was able to solve this by, instead of doing that `DISTINCT` in the outer group by, I just called `.distinct` in the `GlobalAttributeForAPIConverter`. :shrug: 
    ![Screenshot from 2023-02-07 14-31-41](https://user-images.githubusercontent.com/6518824/217389041-e38c0674-6d36-4c26-b493-57e001de43e2.png)

Aside from those two minor things, it all looks amazing. Thank you for making this happen during your super busy quarter!!

2023-02-07 23:20 UTC, merged

2023-02-07 23:26 UTC, jonfroehlich commented
Yes, awesome work @zoekaputa! And thanks @misaugstad for such thoughtful feedback and advice.