Initial PR for removing top Explain This button for feedback
ProjectSidewalk/SidewalkWebpage pull request #3256
Opened 2023-06-13 01:41 UTC by justyeethan

Resolves #3250 

PR for removing the top bar "Explain This" issue. 

Before:
![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/61468547/00777106-ea72-4737-a8e5-7d630e0a007d)

After:
<img width="1011" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/61468547/c9e2eb47-8214-4576-82cd-299e78e0c3b9">

2023-06-13 01:58 UTC, misaugstad commented
Some notes:
1. This was meant to remove the entire bar, not just the 'Explain this' button!
2. When deleting the JavaScript, make sure to check if any HTML, CSS, or translation text is no longer being used anywhere else and delete that as well.
3. You've included a couple other random changes that shouldn't be a part of this PR

2023-06-13 23:20 UTC, justyeethan commented
@misaugstad The new commit reverted the random changes and also removed the entire bar, without changing anything from the mobile view!

2023-06-13 23:41 UTC, misaugstad commented
Great! Did we need to keep all of the text for the Validate page, or is there anything from there that we can remove?

2023-06-14 02:32 UTC, justyeethan commented
Is there specific text that you are looking at to remove? It looks good to me, and it seems there's no redundant code from the changes I've made and the functions I've deleted.

2023-06-22 18:30 UTC, misaugstad requested changes
Okay I didn't exhaustively go through everything, but I noted at least a few examples where translations/code still need to be removed, and one spot where some CSS was removed that shouldn't have been!

Can you go through everything again with a fine-toothed comb?

2023-06-22 18:30 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/Main.js
> -        svl.ui.overlayMessage.holder = $("#overlay-message-holder");
Looks like the HTML element associated with this is still in `explore.scala.html`

2023-06-23 19:06 UTC, misaugstad commented on public/javascripts/SVLabel/src/SVLabel/OverlayMessageBox.js
> -        var instruction = i18next.t('top-ui.instruction.' + util.camelToKebab(mode));
You also missed these, but I am deleting them now as well.

2023-06-23 19:41 UTC, misaugstad approved these changes
Okay I cleaned up a few remaining things so that we could move on to something else!

2023-06-23 19:43 UTC, merged