3221 refactor gallery modal naming
ProjectSidewalk/SidewalkWebpage pull request #3673
Opened 2024-09-30 05:39 UTC by LeeJoh22

Resolves #3221

Refactored Gallery code to replace 'Modal' with 'ExpandedView'.

##### Testing instructions
1. Start local instance
2. Checked functionality and UI of 'Gallery' to ensure consistency before and after changes.

##### Things to check before submitting the PR 

- [x] I've written a descriptive PR title. 
- [x] I've added/updated comments for large or confusing blocks of code.

2024-09-30 18:58 UTC, misaugstad requested changes
Nothing seems to be broken, just a few more changes to make!
* The filename was changed from "Modal.js" to "ExpandedView.js", but the dir it's in is still called "modal".
* Still a reference to "modal" in a comment in "GalleryPanorama.js"
* Still a reference to "modal" in a comment in "ValidationMenu.js"

2024-09-30 18:58 UTC, misaugstad commented on public/javascripts/Gallery/src/displays/SeverityDisplay.js
>          let selectedCircleID = /*isModal ? 'modal-current-severity' : */'current-severity';
At this point we can just remove this variable, it's not doing anything anymore

2024-09-30 18:58 UTC, misaugstad commented on public/javascripts/Gallery/src/displays/SeverityDisplay.js
> +function SeverityDisplay(container,
This can be kept as one line, it's only like 82 characters or smth!

2024-09-30 18:58 UTC, misaugstad commented on public/javascripts/Gallery/src/displays/ValidationInfoDisplay.js
> +function ValidationInfoDisplay(container,
Our default is to keep these param lists on one line, let's just keep it that way for now. Can see an argument for changing that in the future, but let's just stay consistent for now!

2024-09-30 18:58 UTC, misaugstad commented on public/javascripts/Gallery/src/keyboard/Keyboard.js
> +                    ExpandedView.validationMenu.validateOnClickOrKeyPress(
Same with these, let's just keep on one line to keep things looking concise

2024-09-30 18:58 UTC, misaugstad commented on public/javascripts/Gallery/src/modal/ExpandedView.js
> + * A ExpandedView element that provides extended information about a label, along with placing a label in a GSV Panorama
An instead of A :wink:

2024-09-30 20:11 UTC, LeeJoh22 commented
I implemented the comments you left in new commit

2024-09-30 20:55 UTC, misaugstad requested changes
Almost there, just a couple little things to do! I'll get your next task or two ready as well. Thanks for going through some of the tedium of refactoring! Just note how important attention to detail is, given how many comments I ended up leaving!

2024-09-30 20:55 UTC, misaugstad commented on public/javascripts/Gallery/src/keyboard/Keyboard.js
> +function Keyboard(ExpandedView) {
Oh, didn't notice this last time: naming convention for parameters is camelCase, not PascalCase

2024-09-30 20:55 UTC, misaugstad commented on public/javascripts/Gallery/src/displays/SeverityDisplay.js
> +        let selectedCircleID = 'current-severity';
I was suggesting that we fully remove the variable! No need to save the variable and then use it just once.

2024-09-30 20:55 UTC, misaugstad commented on public/javascripts/Gallery/css/expandedview.css
> -.gallery-modal-close {
Oh right, CSS file naming convention is kebab-case!

2024-10-03 20:38 UTC, misaugstad approved these changes
Looks good now, thank you!!

2024-10-03 20:38 UTC, merged