Adding functionality to close and open teams, and also to make teams visible/non visible on the team leaderboard
ProjectSidewalk/SidewalkWebpage pull request #3740
Opened 2024-11-15 20:35 UTC by aslassi777

Resolves #3054 

Replace this with a brief description of the problem solved or feature implemented and how you implemented it.

##### Before/After screenshots (if applicable)

##### Testing instructions
1. 

##### Things to check before submitting the PR 

- [ ] I've written a descriptive PR title. 
- [ ] I've added/updated comments for large or confusing blocks of code.
- [ ] I've included before/after screenshots above.
- [ ] I've asked for and included translations for any user facing text that was added or modified.
- [ ] I've updated any logging. Clicks, keyboard presses, and other user interactions should be logged. If you're not sure how (or if you need to update the logging), ask Mikey. Then make sure the documentation on [this wiki page](https://github.com/ProjectSidewalk/SidewalkWebpage/wiki/Descriptions-of-Logged-Events) is up to date for the logs you added/updated.
- [ ] I've tested on mobile (only needed for validation page).

2024-11-16 00:11 UTC, misaugstad commented
Yess so exciting! Can't wait to take a closer look!!

>I did not take a photo before developing teams page, and I currently do not have admin access to the real sidewalk page.

I think that the best way to do this anyway is to take the "before" screenshots on your local environment when running the develop branch! I usually take the "after" picture, then while I'm writing up the PR I switch back to the develop branch and take the "before" picture. It's honestly best to do it this way because it's a really direct comparison, both pics will be showing the same data since they're both from your dev env!

2024-11-16 00:19 UTC, misaugstad commented
Again, so excited for this!!

And just from looking at the screenshot, let's call "Open/Closed" header "Status" and "Visible/Non-Visible" to "Visibility"! And is there any reason you didn't use the same styling for the drop down menus that we used for the other parts of the Admin page? I'd generally want to just keep things consistent between the different pieces of the Admin page! But ultimately it is just the Admin page, so it's okay to deviate if there's a reason!

2024-11-17 23:38 UTC, aslassi777 commented
All good, I made the changes you requested. No reason not to make it similar to the other pages, so I took care of that in my most recent commit (updated photo so you can check out).

2024-12-26 19:49 UTC, misaugstad requested changes
Looks like you forgot to commit the added evolutions file! So I couldn't actually test the code. I did merge in changes from develop and I'm adding just a couple quick comments from scanning through the code for now.

2024-12-26 19:49 UTC, misaugstad commented on app/controllers/UserProfileController.scala
> +  * Grabs a list of all the teams in the tables,
We can go up to 120 char per line, so no need for a line break

2024-12-26 19:49 UTC, misaugstad commented on app/controllers/UserProfileController.scala
> +    // Convert the list of organizations to JSON
Generally I'd advise against comments like this. With a line like `val teamJson = Json.toJson(teams)`, it feels pretty clear that this line converts to JSON, which feel like we're just cluttering the code more than anything by repeating stuff! Sometimes functions really are just clear enough to have just the method comment! Something as simple as this looks good to me:
```
  /**
  * Grabs a list of all the teams in the database, regardless of open or closed status.
  */
  def getTeams() = UserAwareAction.async { implicit request =>
    val teams: List[Organization] = OrganizationTable.getAllTeams()
    Future.successful(Ok(Json.toJson(teams)))
  }

2024-12-26 19:49 UTC, misaugstad commented on app/views/admin/index.scala.html
> +            $('#teams-tab').on('click', function() {
This should be in public/javascripts/Admin/src/Admin.js where there's similar functionality for the other tabs/tables

2024-12-26 19:49 UTC, misaugstad commented on app/views/admin/index.scala.html
> +            $('#teams-tab').on('click', function() {
I haven't looked at the code for the other tables, but we should be mirroring what's done in those where appropriate!

2024-12-26 19:49 UTC, misaugstad commented on app/views/leaderboard.scala.html
> +            <h1 class="leaderboard-header">@Messages("leaderboard.org.title", OrganizationTable.getOrganizationName(UserOrgTable.getOrg(user.get.userId).get).getOrElse("Team name not found"))</h1>
Not sure if this was a merge conflict or something, but shouldn't we still be using the `orgName` variable defined at the top?

2025-01-28 19:25 UTC, misaugstad approved these changes
I made the necessary changes to make this production-ready!

2025-01-28 19:25 UTC, merged